language: cpp

sudo : false

addons:
  apt:
    packages:
      - cmake

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      env:
        - CC_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls -E ".*gtest.*" -E ".*CMakeFiles.*" --exclude lib --exclude test
            --exclude examples --gcov-options '\-lp'

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - CC_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - CC_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

before_install:
  - eval "${CC_EVAL}"
  - cmake -DBUILD_TESTS=On .

script:
  - make
  - make test

notifications:
  email: false
